export const UPDATE_CURRENTUSERINFO = 'UPDATE_CURRENTUSERINFO' //更新当前登录的用户角色信息
export const UPDATE_RUNTIMELOGDATA = 'UPDATE_RUNTIMELOGDATA' //更新当前系统实时日志

export const UPDATE_RUNTIME_SSTX_LOGDATA = 'UPDATE_RUNTIME_SSTX_LOGDATA' //更新当前系统实时AGV通信日志
export const UPDATE_RUNTIME_SSCZ_LOGDATA = 'UPDATE_RUNTIME_SSCZ_LOGDATA' //更新当前系统实时操作日志
export const UPDATE_RUNTIME_SSYX_LOGDATA = 'UPDATE_RUNTIME_SSYX_LOGDATA' //更新当前系统实时运行日志